title: A&OS 204: Introduction to Machine Learning for Physical Sciences
description: Submitted by Shreya Trivedi  
logo: /assets/IMG/Antarctic_Penguins.png
show_downloads: true
theme: jekyll-theme-Cayman
